Relax restrictions on loading addons in prod until we have a build pi…
starspot/starspot pull request #8
Opened 2016-09-21 21:53 UTC by praxxis

…peline

The current pipeline (`tsc`) removes `package.json` files in prod builds. This meant that addons were discovered but never loaded in production. Now we relax the check in production and load all addons in the addons directory.

2016-09-21 21:54 UTC, praxxis commented
cc @tomdale

2016-09-21 22:36 UTC, tomdale commented on packages/starspot-cli/test/project-test.ts
> +  describe('in-app addons', function () {
double quotes

-Human TSLint

2016-09-21 22:36 UTC, tomdale requested changes

2016-09-22 14:24 UTC, praxxis commented on packages/starspot-cli/test/project-test.ts
> +  describe('in-app addons', function () {
omg

2016-09-22 14:24 UTC, merged